LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := creator_reader

LOCAL_MODULE_FILENAME := libcreatorreader

LOCAL_ARM_MODE := arm

LOCAL_SRC_FILES := \


LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
LOCAL_C_INCLUDES := $(LOCAL_PATH)

include $(BUILD_STATIC_LIBRARY)
